### ISSUE TITLE
`ghcr.io/mewz-project/mewz` can't be pulled

### ISSUE THREAD

**Issue by AkihiroSuda** [mewz-project/mewz#52]
```console
$ docker pull ghcr.io/mewz-project/mewz
Using default tag: latest
latest: Pulling from mewz-project/mewz
af107e978371: Pulling fs layer 
4278792552db: Pulling fs layer 
9c01b7de78bf: Pulling fs layer 
3245434c345b: Waiting 
e438c664582f: Waiting 
1f89fd20aea9: Waiting 
3aff96a866aa: Waiting 
45bc183e102b: Waiting 
7a8408419b6b: Waiting 
7070c6497c75: Waiting 
error pulling image configuration: download failed after attempts=1: unknown blob
```

Some blobs  such as  `sha256:96eb8313ddf564d2d66a262eaa10266ab06aa5933da279021aa3623ce5e740f3` (`application/vnd.docker.container.image.v1+json`) seems missing
https://explore.ggcr.dev/?image=ghcr.io%2Fmewz-project%2Fmewz%40sha256%3A8039c6107729564632b502735086f8d27357e4630e67d665068bb2663e2abab7

**Comment by ainozaki** [comment]
Thank you for the report! I've fixed it now.
(At the moment, the image is quite large and it takes time to pull, but we'll improve it soon.)
