### ISSUE TITLE
Add a test for reading a file

### ISSUE THREAD

**Issue by saza-ku** [mewz-project/mewz#59]
We need a test for reading a file.

- `path_open` to open a file
- `fd_read` to read the file content, and compare it with the expected content
- `fd_close` to close the file

**Comment by saza-ku** [comment]
@dierbei
Could you do this task? This is not urgent work so please take your time!

The integration tests are written [here](https://github.com/mewz-project/mewz/blob/main/src/wasi.zig#L657).
The test will call `path_open`, `fd_read`, and `fd_close`.

Note: `fd_read` gets the address of the receive buffer via the argument of `buf_iovec_addr`, but it is the address of Linear Memory. So we need to convert the address between Linear Memory and the machine's memory, like this: https://github.com/mewz-project/mewz/blob/main/src/wasi.zig#L708

Should you encounter any difficulties or uncertainties, please don't hesitate to reach out for assistance!

**Comment by saza-ku** [comment]
The usage of `fd_read` is almost the same as that of `sock_recv`, so [this](https://github.com/mewz-project/mewz/blob/main/src/wasi.zig#L711) would help you.

**Comment by dierbei** [comment]
Thanks so much, I'm happy to do it.

**Comment by dierbei** [comment]
I'm having some problems with function parameters and have read some documentation : "https://wasix.org/docs/api-reference/wasi/path_open", but I'm not sure if it's relevant.

There are also questions about function parameters, I don't know what each parameter's means.

For some address values I'm currently writing them randomly, I can't know which file to read and how to calculate the address. 

```zig
fn testReadfile(base: usize) bool {
    @setRuntimeSafety(false);

    const fd = @as(*i32, @ptrFromInt(base + 4 + 0xffff800000000000));

    // path_open
    const res = path_open(fd.*, 0, 0, 4, 0, 0, 0, 0, 0);
    if (@intFromEnum(res) != 0) {
        log.fatal.printf("path_open failed: res={d}\n", .{@intFromEnum(res)});
        return false;
    }

    // fd_read
    var ip_iovec_ptr = @as(*IoVec, @ptrFromInt(base + 12 + 0xffff800000000000));
    ip_iovec_ptr.buf = @as(u32, @intCast(base + 8));
    ip_iovec_ptr.buf_len = 4;
    res = fd_read(fd, @as(i32, @intCast(base + 12)), 4, @intCast(base + 8));
    if (@intFromEnum(res) != 0) {
        log.fatal.printf("fd_read failed: {d}\n", .{@intFromEnum(res)});
        return false;
    }

    // fd_close
    res = fd_close(fd);
    if (@intFromEnum(res) != 0) {
        log.fatal.printf("fd_read failed: {d}\n", .{@intFromEnum(res)});
        return false;
    }

    return true;
}
```

**Comment by dierbei** [comment]
@saza-ku It would be nice if `zig` supported unit testing for `wasi`.

That way you can do functional tests locally.

**Comment by saza-ku** [comment]
@dierbei Sorry for being late!

`path_open` is implemented [here](https://github.com/mewz-project/mewz/blob/main/src/wasi.zig#L238).

Actually `dir_flags`, `oflags`, `rights_base`,  `rights_inferiting`, and `fdflags` are ignored in the current implementation.

The important arguments are as below.

- `fd`: The fd of the directory which is relative to the path of the file to open.
- `path_addr`: The address of the string of the path to open.
- `path_len`: The length of the string.
- `opened_fd_addr`: The address of the fd of the opened file. The value is set by `opened_fd_addr`.

So you need to specify `opened_fd_addr` as the variable of `fd`.

`/test.txt` is attached to your VM when running the integration tests. (https://github.com/mewz-project/mewz/blob/59f1e3431d5a1d435ddc2564ba05eca5042a73ca/scripts/create-test-dir.sh)
Please read the file and verify the content!

And `/` is pre-opened after it boots with the fd of 3. So please specify `fd` as 3.

**Comment by dierbei** [comment]
@saza-ku I thought your school had more homework, ahaha.

Okay, I'll give it a shot!

**Comment by dierbei** [comment]
I think I saw this function that creates a file when running `integration tests`.

https://github.com/mewz-project/mewz/blob/dc59c77d34809d07665c4d4995a37b88f816b360/build.zig#L161-L167

Instead, `qemu` should internally use a qualified script to create a file.
https://github.com/mewz-project/mewz/blob/dc59c77d34809d07665c4d4995a37b88f816b360/scripts/create-test-dir.sh#L1-L8

What I'm supposed to do is read the contents of the file inside `qemu` for comparison.

But now I have a problem, how do I go about calculating the file address inside `qemu`? I don't really understand how these files are stored.

```zig
fn testReadfile(base: usize) bool {
    @setRuntimeSafety(false);

     // I'm supposed to be calculating the path_address, path_length, and file handle inside of qemu.
    const file = try std.fs.cwd().openFile("build/test.txt", .{});
    const path = try std.fs.cwd().openDir("build", .{});

    // path_open
    const res = path_open(3, 0, path.fd, 5, 0, 0, 0, 0, file.handle);
    if (@intFromEnum(res) != 0) {
        log.fatal.printf("path_open failed: res={d}\n", .{@intFromEnum(res)});
        return false;
    }
```

**Comment by saza-ku** [comment]
We cannot use most of Zig's standard libraries, because they run on ordinary operating systems such as Linux.

We can specify path by a string, in this way.

```zig
const fd_addr_in_linear_memory = 0;
const path = "test.txt";
// We need to place the string in Linear Memory, which is 0xffff800000000000 to 0xffff8000ffffffff.
// We use address of 4 in Linear Memory.
const path_addr_in_linear_memory = 4;
@memset(@as([*]u8, @ptrFromInt(base + path_addr_in_linear_memory)), path);
const res = path_open(3, 0, path_addr_in_linear_memory, path.len, 0, 0, 0, 0, fd_addr_in_linear_memory);
```

**Comment by dierbei** [comment]
@saza-ku Thanks, I'll give it a try. I feel like it's amazing.

**Comment by dierbei** [comment]
> We cannot use most of Zig's standard libraries, because they run on ordinary operating systems such as Linux.
> 
> We can specify path by a string, in this way.
> 
> ```zig
> const fd_addr_in_linear_memory = 0;
> const path = "test.txt";
> // We need to place the string in Linear Memory, which is 0xffff800000000000 to 0xffff8000ffffffff.
> // We use address of 4 in Linear Memory.
> const path_addr_in_linear_memory = 4;
> @memset(@as([*]u8, @ptrFromInt(base + path_addr_in_linear_memory)), path);
> const res = path_open(3, 0, path_addr_in_linear_memory, path.len, 0, 0, 0, 0, fd_addr_in_linear_memory);
> ```

It looks more like `memcpy`.
```zig
@memcpy(@as([*]u8, @ptrFromInt(base + path_addr_in_linear_memory)), path);
```

but I'm getting an error that I don't quite understand.
```shell
Booting from ROM..
[LOG FATAL]: path_open failed: res=8
+ exit 1
run ./scripts/integration-test.sh: error: the following command exited with error code 1:
./scripts/integration-test.sh 
Build Summary: 7/9 steps succeeded; 1 failed (disable with --summary none)
run transitive failure
└─ run ./scripts/integration-test.sh failure
error: the following build command failed with exit code 1:
```

**Comment by saza-ku** [comment]
> It looks more like memcpy.

Sorry, you're right!

> but I'm getting an error that I don't quite understand.

It's also our mistake. The test directory should be attached when running the integration test, but it fails to do it.
I created a PR to fix it. Please wait for it to be merged!

**Comment by dierbei** [comment]
@saza-ku Ahahaha, no problem.

What's happening now looks like this: the code is making changes to the OS address directly. I haven't played with it that way before!

**Comment by saza-ku** [comment]
Yeah, Mewz achieves the high performance in this way!

Now it's been merged! https://github.com/mewz-project/mewz/pull/61

**Comment by dierbei** [comment]
@saza-ku Is this one because the file doesn't exist or a permissions issue?
```zig
iPXE (http://ipxe.org) 00:03.0 CA00 PCI2.10 PnP PMM+1EFCF000+1EF0F000 CA00
                                                                               


Booting from ROM..
[LOG FATAL]: path_open failed: res=44
+ exit 1
run ./scripts/integration-test.sh: error: the following command exited with error code 1:
./scripts/integration-test.sh 
Build Summary: 8/10 steps succeeded; 1 failed (disable with --summary none)
run transitive failure
└─ run ./scripts/integration-test.sh failure
error: the following build command failed with exit code 1:
```

**Comment by saza-ku** [comment]
This message says that the file is not found. (https://github.com/mewz-project/mewz/blob/main/src/wasi/types.zig#L94)

I guess it fails to specify the path of the file.

Could you show the debug log? You can see it by doing `zig build -Dtest=true -Doptimize=ReleaseFast -Dlog-level=debug run` and `cat build/test/output.txt`.

**Comment by dierbei** [comment]
Wow, I did it. Learned something new again.

The code I was using before looked like this:
```zig
    const fd_addr_in_linear_memory = 0;
    const path = "test.txt";
    const path_addr_in_linear_memory = 4;
    @memcpy(@as([*]u8, @ptrFromInt(base + path_addr_in_linear_memory)), path);
    const res = path_open(3, 0, path_addr_in_linear_memory, path.len, 0, 0, 0, 0, fd_addr_in_linear_memory);
    if (@intFromEnum(res) != 0) {
        log.fatal.printf("path_open failed: res={d}\n", .{@intFromEnum(res)});
        return false;
    }
```

Getting the log looks like this (the file name is empty):
```zig
[LOG INFO]: server socket test: fd_close succeeded
[LOG DEBUG]: WASI path_open: fd:3, dirflags:0, path_offset:4, path_length:8, oflags:0, rights_bas:0, rights_inferiting:0, fdflags:0, opened_fd_addr:0
[LOG DEBUG]: file path: 
[LOG FATAL]: path_open failed: res=44
```

-------
I looked at the first few lines of code in the `path_open` function, and it seems to use `linear_memory_offset` and `path_addr` to calculate the start address of the file name.

So to confirm my suspicions, I made the following changes to the code:
``zig
    @memcpy(@as([*]u8, @ptrFromInt(linear_memory_offset + path_addr_in_linear_memory)), path);
``

I finally got a successful log:
```zig
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.0DH:EAX.xsavec [bit 1]
+ curl localhost:1234
curl: (1) Received HTTP/0.9 when not allowed
+ QEMU_RETURN_CODE=1
+ RETURN_CODE=0
+ exit 0
+ grep -q 'Integration test passed' build/test/output.txt
+ echo -e '\nIntegration Test PASSED!!'
```

I understand his structure to be about this：
![image](https://github.com/mewz-project/mewz/assets/52097565/f5fa78f4-01d7-45ef-b57d-5a3edca1554f)

What puzzles me though is that using `base + 
path_addr_in_linear_memory` will fail, `base` is passed in on this side：https://github.com/mewz-project/mewz/blob/main/src/wasi.zig#L642-L644

**Comment by saza-ku** [comment]
Great! Your understanding is correct. Good job!

I guess the following code would work.

```
    const fd_addr_in_linear_memory = base + 0;
    const path = "test.txt";
    const path_addr_in_linear_memory = base + 4;
    @memcpy(@as([*]u8, @ptrFromInt(path_addr_in_linear_memory + linear_memory_offset)), path);
```

`base` is the offset of the memory region the test codes can use **in Linear Memory Address**. And I think the value is 0.

It's a little confusing, so it would be better to delete `base`.

**Comment by dierbei** [comment]
@saza-ku The implementation of `fd_close()` looks like this, I'm not sure if it's correct.

As I understand it, fd should correspond to a handle to some `file`. I don't know how to get the `file` handle so far.

```zig
    // fd_close
    res = fd_close(3);
    if (@intFromEnum(res) != 0) {
        log.fatal.printf("fd_read failed: {d}\n", .{@intFromEnum(res)});
        return false;
    }
```

**Comment by saza-ku** [comment]
First, the file descriptor of the test file is stored at `fd_addr_in_linear_memory + linear_memory_base`. It's set in `path_open`. (https://github.com/mewz-project/mewz/blob/main/src/wasi.zig#L264)

Second, `fd_read` is like `readv` in POSIX. You can learn about iovec [here](http://www.redwoodsoft.com/~dru/unixbook/book.chinaunix.net/special/ebook/addisonWesley/APUE2/0201433079/ch14lev1sec7.html).

Third, the content of the test file is [here](https://github.com/mewz-project/mewz/blob/main/scripts/create-test-dir.sh#L8). We need larger buffer to store it.

```zig
    buf_iovec_ptr.buf = 32;
    buf_iovec_ptr.buf_len = 1024;
```

**Comment by dierbei** [comment]
> 首先，测试文件的文件描述符存储在 `fd_addr_in_linear_memory + linear_memory_base` 处。它设置在 `path_open` 中。 （https://github.com/mewz-project/mewz/blob/main/src/wasi.zig#L264）

Thank you! I'll start with my understanding.

will get a pointer to an i32 from the `fd_addr_in_linear_memory + linear_memory_offset` to the `fd_addr_in_linear_memory + linear_memory_offset + 4`

```zig
    // fd_close
    const open_fd = @as(*i32, @ptrFromInt(fd_addr_in_linear_memory + linear_memory_offset));
    res = fd_close(open_fd.*);
    if (@intFromEnum(res) != 0) {
        log.fatal.printf("fd_read failed: {d}\n", .{@intFromEnum(res)});
        return false;
    }
```

Use `fd.*` to fetch the value of the file descriptor, then go to `fd_table` and delete the corresponding element (`fd_table` looks like an `array`)

https://github.com/mewz-project/mewz/blob/0c5853c849eed8a8c66d4c056bb47f4a4d204739/src/stream.zig#L32-L41

**Comment by dierbei** [comment]
@saza-ku I ran into a problem first and wasn't sure how to fix it.

```zig
    const open_fd = @as(*i32, @ptrFromInt(fd_addr_in_linear_memory + linear_memory_offset));

    var buf_iovec_ptr = @as(*IoVec, @ptrFromInt(path_addr_in_linear_memory + 20));
    buf_iovec_ptr.buf = 32;
    buf_iovec_ptr.buf_len = 1024;
    res = fd_read(open_fd.*, @as(i32, @intCast(path_addr_in_linear_memory + 20)), 8, @intCast(path_addr_in_linear_memory + 8 + 20));
    if (@intFromEnum(res) != 0) {
        log.fatal.printf("fd_read failed: {d}\n", .{@intFromEnum(res)});
        return false;
    }

    // fd_close
    res = fd_close(open_fd.*);
    if (@intFromEnum(res) != 0) {
        log.fatal.printf("fd_read failed: {d}\n", .{@intFromEnum(res)});
        return false;
    }

-----
[LOG DEBUG]: WASI path_open: fd:3, dirflags:0, path_offset:4, path_length:8, oflags:0, rights_bas:0, rights_inferiting:0, fdflags:0, opened_fd_addr:0
[LOG DEBUG]: file path: test.txt
[LOG DEBUG]: WASI fd_read: fd=7 buf_iovec_addr=0x18 vec_len=8 size_addr=0x20
[LOG FATAL]: fd_read failed: 48
+ exit 1
```

https://github.com/mewz-project/mewz/blob/0c5853c849eed8a8c66d4c056bb47f4a4d204739/src/wasi/types.zig#L101-L102

**Comment by saza-ku** [comment]
You should specify `1` to `buf_len` in `fd_read`, because it's the size of iovecs.

```
    res = fd_read(open_fd.*, @as(i32, @intCast(path_addr_in_linear_memory + 20)), 1, @intCast(path_addr_in_linear_memory + 8 + 20));
```

**Comment by dierbei** [comment]
> You should pass `1` to `ven_len` in `fd_read`, because it's the number of iovecs.

I thought it was the number of bytes taken up by `buf_iovec_ptr`.

**Comment by saza-ku** [comment]
Yeah it's a little confusing :sweat_smile:

[This page](http://wasix.org/docs/api-reference/wasi/fd_read) might help you understand the meaning of WASI arguments.

**Comment by saza-ku** [comment]
Closed by https://github.com/mewz-project/mewz/pull/64.

Thanks @dierbei
